export const LOCALIZED_BOOK_NAMES: Record<string, Record<string, string>> = {
  "TBSI": {
    "genesis": "ஆதியாகமம்",
    "exodus": "யாத்திராகமம்",
    "leviticus": "லேவியராகமம்",
    "numbers": "எண்ணாகமம்",
    "deuteronomy": "உபாகமம்",
    "joshua": "யோசுவா",
    "judges": "நியாயாதிபதிகள்",
    "ruth": "ரூத்",
    "1samuel": "1 சாமுவேல்",
    "2samuel": "2 சாமுவேல்",
    "1kings": "1 இராஜாக்கள்",
    "2kings": "2 இராஜாக்கள்",
    "1chronicles": "1 நாளாகமம்",
    "2chronicles": "2 நாளாகமம்",
    "ezra": "எஸ்றா",
    "nehemiah": "நெகேமியா",
    "esther": "எஸ்தர்",
    "job": "யோபு",
    "psalms": "சங்கீதம்",
    "proverbs": "நீதிமொழிகள்",
    "ecclesiastes": "பிரசங்கி",
    "songofsolomon": "உன்னதப்பாட்டு",
    "isaiah": "ஏசாயா",
    "jeremiah": "எரேமியா",
    "lamentations": "புலம்பல்",
    "ezekiel": "எசேக்கியேல்",
    "daniel": "தானியேல்",
    "hosea": "ஓசியா",
    "joel": "யோவேல்",
    "amos": "ஆமோஸ்",
    "obadiah": "ஒபதியா",
    "jonah": "யோனா",
    "micah": "மீகா",
    "nahum": "நாகூம்",
    "habakkuk": "ஆபகூக்",
    "zephaniah": "செப்பனியா",
    "haggai": "ஆகாய்",
    "zechariah": "சகரியா",
    "malachi": "மல்கியா",
    "matthew": "மத்தேயு",
    "mark": "மாற்கு",
    "luke": "லூக்கா",
    "john": "யோவான்",
    "acts": "அப்போஸ்தலர்",
    "romans": "ரோமர்",
    "1corinthians": "1 கொரிந்தியர்",
    "2corinthians": "2 கொரிந்தியர்",
    "galatians": "கலாத்தியர்",
    "ephesians": "எபேசியர்",
    "philippians": "பிலிப்பியர்",
    "colossians": "கொலோசெயர்",
    "1thessalonians": "1 தெசலோனிக்கேயர்",
    "2thessalonians": "2 தெசலோனிக்கேயர்",
    "1timothy": "1 தீமோத்தேயு",
    "2timothy": "2 தீமோத்தேயு",
    "titus": "தீத்து",
    "philemon": "பிலேமோன்",
    "hebrews": "எபிரெயர்",
    "james": "யாக்கோபு",
    "1peter": "1 பேதுரு",
    "2peter": "2 பேதுரு",
    "1john": "1 யோவான்",
    "2john": "2 யோவான்",
    "3john": "3 யோவான்",
    "jude": "யூதா",
    "revelation": "வெளிப்படுத்தல்"
  },
  "TELIRV": {
      "genesis": "ఆదికాండము",
      "exodus": "నిర్గమకాండము",
      "leviticus": "లేవీయకాండము",
      "numbers": "సంఖ్యాకాండము",
      "deuteronomy": "ద్వితీయోపదేశకాండము",
      "joshua": "యెహోషువ",
      "judges": "న్యాయాధిపతులు",
      "ruth": "రూతు",
      "1samuel": "1 సమూయేలు",
      "2samuel": "2 సమూయేలు",
      "1kings": "1 రాజులు",
      "2kings": "2 రాజులు",
      "1chronicles": "1 దినవృత్తాంతములు",
      "2chronicles": "2 దినవృత్తాంతములు",
      "ezra": "ఎజ్రా",
      "nehemiah": "నెహెమ్యా",
      "esther": "ఎస్తేరు",
      "job": "యోబు",
      "psalms": "కీర్తనలు",
      "proverbs": "సామెతలు",
      "ecclesiastes": "ప్రసంగి",
      "songofsolomon": "పరమగీతము",
      "isaiah": "యెషయా",
      "jeremiah": "యిర్మీయా",
      "lamentations": "విలాపవాక్యములు",
      "ezekiel": "యెహెజ్కేలు",
      "daniel": "దానియేలు",
      "hosea": "హోషేయ",
      "joel": "యోవేలు",
      "amos": "ఆమోసు",
      "obadiah": "ఓబద్యా",
      "jonah": "యోనా",
      "micah": "మీకా",
      "nahum": "నహూము",
      "habakkuk": "హబక్కూకు",
      "zephaniah": "జెఫన్యా",
      "haggai": "హగ్గయి",
      "zechariah": "జెకర్యా",
      "malachi": "మలాకీ",
      "matthew": "మత్తయి సువార్త",
      "mark": "మార్కు సువార్త",
      "luke": "లూకా సువార్త",
      "john": "యోహాను సువార్త",
      "acts": "అపొస్తలుల కార్యములు",
      "romans": "రోమీయులకు",
      "1corinthians": "1 కొరింథీయులకు",
      "2corinthians": "2 కొరింథీయులకు",
      "galatians": "గలతీయులకు",
      "ephesians": "ఎఫెసీయులకు",
      "philippians": "ఫిలిప్పీయులకు",
      "colossians": "కొలొస్సయులకు",
      "1thessalonians": "1 థెస్సలొనీకయులకు",
      "2thessalonians": "2 థెస్సలొనీకయులకు",
      "1timothy": "1 తిమోతికి",
      "2timothy": "2 తిమోతికి",
      "titus": "తీతుకు",
      "philemon": "ఫిలేమోనుకు",
      "hebrews": "హెబ్రీయులకు",
      "james": "యాకోబు",
      "1peter": "1 పేతురు",
      "2peter": "2 పేతురు",
      "1john": "1 యోహాను",
      "2john": "2 యోహాను",
      "3john": "3 యోహాను",
      "jude": "యూదా",
      "revelation": "ప్రకటన గ్రంథము"
  }
};

export function getBookName(bookId: string, fallbackName: string, version?: string): string {
  if (version && LOCALIZED_BOOK_NAMES[version] && LOCALIZED_BOOK_NAMES[version][bookId]) {
    return LOCALIZED_BOOK_NAMES[version][bookId];
  }
  return fallbackName;
}
