// GENERATED by scripts/gen-chapter-art.cjs — do not edit by hand.
//
// How many chapters of each book have artwork, counting from chapter 1. Books with no
// art at all are absent.
//
// This exists because the scheduler has to know, before it builds a card, whether a
// plate can be shown. Asking "what anchors this chapter?" over a picture is a different
// and easier question than asking it cold, and the review history records which was
// asked — so a book with no art silently answering the easy question while logging the
// hard one made that field untrue for a quarter of the canon.
//
// 49 books, 790 plates.
export const CHAPTER_ART: Record<string, number> = {
  '1corinthians': 16,
  '1john': 5,
  '1peter': 5,
  '1thessalonians': 5,
  '1timothy': 6,
  '2corinthians': 13,
  '2john': 1,
  '2peter': 3,
  '2thessalonians': 3,
  '2timothy': 4,
  '3john': 1,
  acts: 28,
  amos: 9,
  colossians: 4,
  daniel: 12,
  ephesians: 6,
  exodus: 40,
  ezekiel: 48,
  galatians: 6,
  genesis: 50,
  habakkuk: 3,
  haggai: 2,
  hebrews: 13,
  hosea: 14,
  isaiah: 66,
  james: 5,
  jeremiah: 52,
  joel: 3,
  john: 21,
  jonah: 4,
  jude: 1,
  lamentations: 5,
  leviticus: 27,
  luke: 24,
  malachi: 4,
  mark: 16,
  matthew: 28,
  micah: 7,
  nahum: 3,
  numbers: 13,
  obadiah: 1,
  philemon: 1,
  philippians: 4,
  psalms: 150,
  revelation: 22,
  romans: 16,
  titus: 3,
  zechariah: 14,
  zephaniah: 3,
};

/** Whether a plate exists for this chapter, and so whether it can be used as a prompt. */
export function hasChapterArt(bookId: string, chapter: number): boolean {
  return chapter >= 1 && chapter <= (CHAPTER_ART[bookId] ?? 0);
}
