// Generated by scripts/fetch_cross_references.js — do not edit by hand.
// The query string is a content hash: it changes only when the dataset does, so browsers
// re-download the file after a regeneration and cache it normally the rest of the time.
export const CROSS_REFS_URL = '/data/cross_references.json?v=f0ae3447';
